version: '2.1'

services:
  mohanalatest171121:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/mohanalatest171121
    ports:
      - $SERVER_PORT:$SERVER_PORT
